title: OreMine Wiki
description: База знаний гриферского Minecraft-сервера OreMine
lang: ru-RU
url: "https://wiki.oremine.me"
markdown: kramdown
permalink: pretty
exclude:
  - compose.yaml
  - Dockerfile
  - README.md
